### ISSUE TITLE
Add code view to example pages

### ISSUE THREAD

**Issue by nateplusplus** [nateplusplus/pushin#229]
Example pages like https://nateplusplus.github.io/pushin/examples/simple/ could use an easy way to see the source code, so that they can be used as code examples.

- [ ] Add sub-navigation to example pages
- [ ] Options for subnav: Result, Vanilla, React
  - [ ] Clicking on Result should show the example as a demo
  - [ ] Clicking on Vanilla should show plain HTML and vanilla JS code used to create the example
  - [ ] Clicking on React should show a React code snippet that can be used to create the example

**Comment by Dhananjay-12** [comment]
hi @nateplusplus I am interested in this one.

**Comment by nateplusplus** [comment]
Hi @Dhananjay-12 that's great to hear! Are you interested in working on this?

I recently moved the documentation site over to a separate repository in an effort to clean up the plugin code a little better.

If you want to work on this as a contribution, I've copied this issue over to the new repo here: https://github.com/nateplusplus/pushin-docs/issues/2

**Comment by nateplusplus** [comment]
I'm closing this issue since it is now moved to the pushin-docs repo.

You can continue following progress on this enhancement here: https://github.com/nateplusplus/pushin-docs/issues/2
