### ISSUE TITLE
Change repo name to match package name

### ISSUE THREAD

**Issue by nateplusplus** [nateplusplus/pushin#84]
I think we should change the repository name (pushin-js) to match the package name (pushin) to reduce any confusion and keep things as simple as possible.

As far as I can tell, there should be no negative consequences for those already using the package. It's unclear what happens to forked repos.

**Comment by nateplusplus** [comment]
@arturovt  I'm curious to get your opinion on this idea

**Comment by arturovt** [comment]
Hey, this is safe to rename the repo, just need to update references within package.json.

**Comment by nateplusplus** [comment]
@arturovt Ah good point, thanks! I'll hold off on this until we finish up the typescript refactor.

**Comment by nateplusplus** [comment]
I have updated references and changed the repo name. This will be released with v4.

Sadly I didn't think about how the prerelease status means that the latest release does not have these changes. I think the effects are pretty minimal though... just some broken links here and there. With our current velocity, I think we'll make enough progress where we can release a stable v4 pretty soon.
